---
apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: webhook-secret
  namespace: webhook
data:
  # Just some self signed keys and certificates, to make it work.
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1akNDQWFJQ0NRQ3hLUEVQNmJuUitEQU5CZ2txaGtpRzl3MEJBUVVGQURBWU1SWXdGQVlEVlFRRERBMU4KZVNCMllXeHBaR0YwYVc5dU1CNFhEVEl4TURJeU16RTVORFkwT0ZvWERUSXhNRE15TlRFNU5EWTBPRm93SmpFawpNQ0lHQTFVRUF3d2JkMlZpYUc5dmF5MXpaWEoyYVdObExuZGxZbWh2YjJzdWMzWmpNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwYkpiZ0VGeStRNituVDl0aU1HamM0Q0k2MU9ibHQ1My9HN0QKdHV2eW9vc1BEZ2RrMWl1ZTdWYlZpUlNpR3k3ekMydnc5NlJuTzNOaWUwWlZhYmRBb21yTVhDSGE0YUNmK3YwSQp6Vy9VSWhDa3c4MldrSWZQVVNZMFhybEpleXdXUFU2WVZYUytnYlJtSVJiNzJEUGxnWFRrS3Q4NWM3T3RqR1ZlCld3VjRtQTU5VmZGREwzMmJCRVVvaXJiaEYvWEZsdGZ6U2NGeDBCbVg2d0s3TzR4cXpiUmlvV3E3SUMzU0FJVFQKNXQ2Tnl2ejRhWm5uWFdXR2VmK3l1MS9zVm9KSjdRdUxoSTVwYjdjZ2w2bFljVjMxem9IK1d6eGFGN1c4OU1NKwpqZVo4SlBIa3Vra01Cek9aSUpySnV2d2Q3cGVpUmd3ekRSUi9oODk4SmFPNUVyM2oyUUlEQVFBQk1BMEdDU3FHClNJYjNEUUVCQlFVQUE0SUJBUUJPQ0pmcnh0Vld2RUptbjNVT2JNOTNGVXRveUFFSEhpc3ZIa1Z2Q2J1YnhvMFYKMUxKbFA1MldvMkpkSTVpUFMrN1lEWGZvcklqZGkzNWtNaWplNFFNOXo1dnhDVjRzZHdVRHJ6Q3Z3U0dWMEorbwpVTkRwMXk5Zlpjb3VlQUZVVDJBYkp5Rnk2NU1xeTU1T3J0QWZ3WmpSWFRWNS9nN3grMEVMYVBqODQ0Q3N6UE5xCjdqQnJrUllhcTBaenh1Lyt6UndrbkNyUFRkWFh1dkw5aDB1UDdvMlVud3c2TkMzVjR2RkYxOEE3a0thU241eXkKTjkzY1pnZjlKbUVOODgxT1E0bkFwN25HbDIyRC9YUUJyN0RTRURwd3hMOHB6dEhSdjRSdWR6cWxjMzk2Y2J2Qgp3bVZVUkRKaFFLMzUzb29hT0sxVWRHMWRYY0Nic3ZRNlUra1VtNkZQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcGJKYmdFRnkrUTYrblQ5dGlNR2pjNENJNjFPYmx0NTMvRzdEdHV2eW9vc1BEZ2RrCjFpdWU3VmJWaVJTaUd5N3pDMnZ3OTZSbk8zTmllMFpWYWJkQW9tck1YQ0hhNGFDZit2MEl6Vy9VSWhDa3c4MlcKa0lmUFVTWTBYcmxKZXl3V1BVNllWWFMrZ2JSbUlSYjcyRFBsZ1hUa0t0ODVjN090akdWZVd3VjRtQTU5VmZGRApMMzJiQkVVb2lyYmhGL1hGbHRmelNjRngwQm1YNndLN080eHF6YlJpb1dxN0lDM1NBSVRUNXQ2Tnl2ejRhWm5uClhXV0dlZit5dTEvc1ZvSko3UXVMaEk1cGI3Y2dsNmxZY1YzMXpvSCtXenhhRjdXODlNTStqZVo4SlBIa3Vra00KQnpPWklKckp1dndkN3BlaVJnd3pEUlIvaDg5OEphTzVFcjNqMlFJREFRQUJBb0lCQUdHTjNmTm9GVUh2WFdpRgpaSDdreXRBQStCdmM4TGpscUN6MkpjSjNyalhtdTJsZUR3OU5SVmVsRFRtVTdWQWwxekI5VDdUdGxWM2FORHd5CkQ2MmJGN0hJUVNOcFIwNFozTGJQN1RQT3lFMTZFUmU2M2crZjlmNW9DT05RSWFRa003L0ttME9NNVhERi9tOHkKOGZtN3JEOEl6Q0UxcGNTcUg5Nk4rL3lJL3hRK1dRRmN4d3paVjRBZ0RyMVkxWTYvWCtxd0VJQkpndzcrd1UzbwpkN0dDcTU0cXV4d05PMktFZVNXZHVpRnZSR0FTdVNlMy9uU1FFeUo2djJaRUtBd0JFMnJHcmRvcXlLKzZLclhHCndNZXI5WnpvaVlxcTNIbTJFMisrczBMZlk3RGJOL1FwTzF2QkVRRjR5UnZmc3FreENpSmwxd1pyMTVNR1VhZG0KQitVNVVjVUNnWUVBMVNHWnR4M1Z0MDZNelB3V0ZaYmc0T3JDRTIvVVkzMjQvb2tITVhkdXFPcnl1OWVQQnB1Qgo1UTFkK2F2RGRKTmFEc0pQT0NiUFdEQjFRUXo5Y01PVFV3Q2hPeDFtaUNlTmZITDZoY0J1RDI3Yk9ScGthNENKCnNPYkdQdlI4WXBZUU13ZWhaQy96a01KR3prd2dSNUF1aEtBamNwbmdKQnRjeTBHdkY4K3E3cU1DZ1lFQXh3WksKdlV0WGlub0VjN0s1UlYrTExCMUE4aFoyQUNQYkpaSFIvb2w0UFpkRHRiSzRnd1MxZ2lGbzVWNlY2aXpPMGRUNwo0N2trQzhoN3ZGa1pPaFR0Sm9XWEREWm1WdzdIdEJTSm9BdXdOSEh2aVhYQ1d1RGFlUEhQVGlGbEhyejY2ZlVuClBvQnlDL0tZV3dWK2l4UTBGUnpxZ0NHb2hIeVhTSk1zYlFNVXQxTUNnWUVBbjZ4enFBL1BER3pwNmF5MnN1ZjkKaENQODBHa0l1cHozR3FMNFk2UHhvTldja3dRMG9DT2pGa0tFZEVldHdFbWd2OHZ0WThrWHNCOWx5UjE5UnAwUApZN0RtR2c2MXdTMjR2MUs0dzduZCt1djNpM2x0WUdqRlAyWTFnZmJTdFYxdHQzMXcrVWsvZGVWRy9NbGxxWmVvCmNpNHpRR2x0MWo4MXJ3Vi9zeHdmR0hjQ2dZQi9KaURua0ZPc0QwbjYxSXFTckhpUVJWd3hqWEh6b3ZTbHF1UmEKMWw1d0VzeGFMNFM3aDIyaVprL0tnY1FLNkhkMURMbWtBYXJxc0RtRTJmTkk3UWVaSGEyalNyblZFb2M1SUFuUQpxc2IycW5lYS9SV2UwNW9mdkhSeGVOcE9hZk52Tm9UTTVHaDRBNU9jU3dWT095a085L3RFd3J3VGNEbUNUeXdKCnRQY3VLd0tCZ0RIcEl1dlVERjJkb1d3US85cTBZMEtWc0dvdGtSZ1dBQjFhRVJYUUVRekFsOGI5SWQvbmxTb0cKWjM5Vm5pWFRMZWM5QitZUUwzd2hlRWFyRzE5OXlNbzIxWUtObWN5bEp2K2c4SExNVkpIMHNPTVVHZTVNck53RwpGL3FzRm41eWx6TWU2TVpIRXZJOFFFSHJ0TjkyMGRlbkpwa0NJZ3BUbThpSlN4dGZJd3lKCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook
webhooks:
  - name: pod.validation.webhook
    clientConfig:
      service:
        name: webhook-service
        namespace: webhook
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQ1RaaWR3L3FXVHd6QU5CZ2txaGtpRzl3MEJBUXNGQURBWU1SWXdGQVlEVlFRRERBMU4KZVNCMllXeHBaR0YwYVc5dU1CNFhEVEl4TURJeU16RTVORFUwTmxvWERUSXhNRE15TlRFNU5EVTBObG93R0RFVwpNQlFHQTFVRUF3d05UWGtnZG1Gc2FXUmhkR2x2YmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUxjK1FmUU9Vd0RyMS9MYTBidnc0bXlOekV4UktMZUxIZjNvRW1TeEZ2djdWbXpJQlFxOFVHek0KWU1nbXZXdGpZSm83RHJIcWZPSEJPeW13NTdsOUFJYW1oNEQydXZ3NGNUNS94T0d5OG1VOTNKSzlNd0taY2xneAprdzZONlpQMWtsS3c3WGVxbitsdE9iQjloRlE1NnhFQ3k4aTF5RG83WThYVHoxSEMybVJiZzUwdjlSSCtDY2FXClROcUwyV1JFU0hzQ1gvaXJEZDZYZ3BjOW9pYWNYa3RSV3ZlK0J4MHU0ZzhsZTVQK0R0ckF1aDZGOS9GS1JyQjcKYllReDNUanBiOFpCQ3JZOUlIOFlZZC85WXBPRWdzZDlvbWREeUNIcE9wV2tWOUx6WFlVTzhpbTJLNGNpaS8vWQpDSHZCMlV3dTdObDhmY1dyMHE2SjhkeDJhRURUR3A4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCk5aUjJzaDdpVnBucmh6dXBOd2diU29kZ0IxK2RHbUxyQkR4MzlLckNTREVHSDZiZU02cHNhL1VIeVM2QXk0WTEKSk4vQXVLWEJmOWF3dkR4MHNndE9yYzVkTHE4cTJPUmZGMmFuWDR0UWxVSlJBNk9xamZjaWFqTURVKzQ4VHBNeQpQVWdUczVYZG52eC9WOWpKYlpzRnZHOG9LZDhtNjk4WU9jS2JCWEFhS1JDVHRsUi90dDFHWEZHMG8vd3hJNVd1CndpZUEzWTkvUU1mRVIxNzF0UGVndHpwQWRUd2ZMQXBBSmlva0E4b3Z4ck8vVm5FMU9Sb3RPa1QxT0hUaHFldWYKNG93SXVJelZtbFhERk5PMTRBMzFQYVRYRUJwNjUzelVYYzFaeHBzblJqVExhaW4vK0cwa1ZmYm1wSU5xRGJZeAo3d3VnSXhSU3dUT3Y1YzdQdUNPZi9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: myworkflow
          operator: In
          values: ["mytest"]
    matchPolicy: Equivalent
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: webhook
spec:
  selector:
    app: validation-webhook
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook-deployment
  namespace: webhook
  labels:
    app: validation-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-webhook
  template:
    metadata:
      labels:
        app: validation-webhook
    spec:
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-secret
      containers:
        - name: server
          image: mywebhook:1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-certs
              mountPath: /tmp/tls-certs
              readOnly: true
